
# Settings for ros_control hardware interface
hardware_interface:
    joints:
      - base_arm
      - second_stage_arm
    sim_control_mode: 0  # 0: position, 1: velocity
    
super_smooth_moves:
  type: position_controllers/JointTrajectoryController
  joints:
    - base_arm
    - second_stage_arm
  gains:
    base_arm:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    second_stage_arm:
      p: 100
      d: 1
      i: 1
      i_clamp: 1

# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

moveit_sim_hw_interface:
    joint_model_group: controllers_initial_group_
    joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
    loop_hz: 100
    cycle_time_error_threshold: 0.01

