authors: []
blacklist:
- ackermann_steering_controller
- ar_track_alvar
- color_spin
- controllers_2020
- controllers_2020_msgs
- diff_drive_controller
- effort_controllers
- force_torque_sensor_controller
- four_wheel_steering_controller
- goal_detection
- gripper_action_controller
- robot_characterization
- rqt_joint_trajectory_controller
- realsense2_camera
- realsense2_description
- robot_visualizer
- turing_smart_screen
- velocity_controllers
- zed_ros
build_space: build
catkin_make_args: []
cmake_args:
- -DCATKIN_ENABLE_TESTING=OFF
- -DBUILD_WITH_OPENMP=ON
- -DCMAKE_CXX_STANDARD=17
- -DSETUPTOOLS_DEB_LAYOUT=OFF
devel_layout: linked
devel_space: devel
extend_path: null
extends: null
install: false
install_space: install
isolate_install: false
jobs_args: []
licenses:
- TODO
log_space: logs
maintainers: []
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
