authors: []
blacklist:
- moveit_ros_robot_interaction
- moveit_ros_benchmarks
- moveit_ros_manipulation
- moveit_chomp_optimizer_adapter
- moveit_planners_chomp
- chomp_motion_planner
- ackermann_steering_controller
- adi_driver
- adi_pico_driver
- ar_track_alvar
- color_spin
- controllers_2019
- controllers_2019_msgs
- controllers_2020
- controllers_2020_msgs
- controllers_2022
- controllers_2022_msgs
- deeptag_ros
- diff_drive_controller
- effort_controllers
- force_torque_sensor_controller
- four_wheel_steering_controller
- goal_detection
- gripper_action_controller
- navx_publisher
- robot_characterization
- realsense2_camera
- realsense2_description
- robot_visualizer
- rosserial_arduino
- rosserial_chibios
- rosserial_embeddedlinux
- rosserial_mbed
- rosserial_server
- rosserial_test
- rosserial_tivac
- rosserial_vex_cortex
- rosserial_vex_v5
- rosserial_windows
- rosserial_xbee
- spinnaker_camera_driver
- teraranger_array
- teraranger_array_converter
- turing_smart_screen
- velocity_controllers
- zed_ros
- wpilib_swerve_odom
build_space: build
catkin_make_args: []
cmake_args: []
devel_layout: linked
devel_space: devel
extend_path: null
extends: null
install: false
install_space: install
isolate_install: false
jobs_args: []
licenses:
- TODO
log_space: logs
maintainers: []
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
