# ros_control_boilerplate Settings -----------------------
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 25
  cycle_time_error_threshold: 0.01

# Settings for ros_control hardware interface
hardware_interface:
   joints:
      - base_arm
      - second_stage_arm
   sim_control_mode: 0 # 0: position, 1: velocity
   port: /dev/ttyUSB0

# Publish all joint states ----------------------------------
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: 50

base_arm:
   type: servo
   port: 1
   inverted: false
   offset: 1.606706 # 17 deg + 90ish deg

second_stage_arm:
   type: servo
   port: 2
   inverted: true
   offset: 1.13446 # 65 deg
# Individual Position Controllers ---------------------------------------
# Allows to send individual ROS msg of Float64 to each joint separately

minifrc_arm_joint_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - base_arm
    - second_stage_arm
