# ros_control_boilerplate Settings -----------------------
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 25
  cycle_time_error_threshold: 0.01

# Settings for ros_control hardware interface
hardware_interface:
   joints:
      - base_arm
      - second_stage_arm
      - fr_drive
      - fl_drive
      - br_drive
      - bl_drive
      - intake
   sim_control_mode: 0 # 0: position, 1: velocity
   port: /dev/rfcomm0

# Publish all joint states ----------------------------------
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: 50

fr_drive:
   type: motor
   port: 3
   inverted: false
   velocity_mult: 1.0
   velocity_feed_forward: 0.0

fl_drive:
   type: motor
   port: 2
   inverted: true
   velocity_mult: 1.0
   velocity_feed_forward: 0.0

br_drive:
   type: motor
   port: 4
   inverted: false
   velocity_mult: 1.0
   velocity_feed_forward: 0.0
   
bl_drive:
   type: motor
   port: 1
   inverted: true
   velocity_mult: 1.0
   velocity_feed_forward: 0.0

intake:
   type: motor
   port: 6
   inverted: true
   velocity_mult: 1.0
   velocity_feed_forward: 0.0

base_arm:
   type: servo
   port: 1
   inverted: false
   offset: 1.57 # 90 deg
   scale: 1.0

second_stage_arm:
   type: servo
   port: 4
   inverted: false
   offset: 0.0 # 65 deg
   scale: 1.667

# Individual Position Controllers ---------------------------------------
# Allows to send individual ROS msg of Float64 to each joint separately

# joint trajectory controller for arm
minifrc_arm_joint_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - base_arm
    - second_stage_arm

intake_controller:
  type: velocity_controllers/JointVelocityController
  joint: intake

mecanum_drive_controller:
  type: minimotor/MecanumDriveController
  # add parameters sometime maybe